export enum EVENTS {
  PageView = 'PV',
  ConnectClick = 'User_Connect',
  ConnectSucceed = 'User_Connect_Succeed',
  ConnectGetAddress = 'User_Get_Xpub',
  SendClick = 'User_Click_Send',
  SendConfirm = 'User_Send_Comf',
  SendSign = 'User_Send_Sign',
  TopUp = 'TopUp',
  TransactionBroadcast = 'Trans_Broadcast',
  TransactionBroadcastSucceed = 'Trans_Broadcast_Succ',
  TransactionButton = 'Transaction_Button',
  LightningSetup = 'Lightning_Setup',
  LightningAddSuccess = 'Lightning_Add_Success',
  LightningWalletAmount = 'Lightning_Wallet_Amount',
  LightningImportSuccess = 'Lightning_Import_Success',
  LightningReceive = 'Lighting_Receive',
  LightningSend = 'Lighting_Send',
  LightningBackupWallet = 'Lighting_Backup_Wallet',
}
