#!/bin/sh

set -eu

cd $(dirname $0)/..

if [ $ENV == 'staging' ];then
  export AWS_DEFAULT_REGION="eu-west-1"
else
  export AWS_DEFAULT_REGION="eu-central-1"
fi

auto/shush encrypt alias/keystone  < environments/.env.${ENV} > environments/.env.${ENV}.encrypted
