#!/bin/bash

set -eu

if [[ -n ${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI:-} ]];then
  credential=$(curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI)
  export AWS_ACCESS_KEY_ID=$(echo $credential | jq -r .AccessKeyId)
  export AWS_SECRET_ACCESS_KEY=$(echo $credential | jq -r .SecretAccessKey)
  export AWS_SESSION_TOKEN=$(echo $credential | jq -r .Token)
else
  credential=$(aws sts assume-role --role-arn arn:aws:iam::623147552995:role/buildkite_agent_deploy --role-session-name=btcsnap --output=json)
  export AWS_ACCESS_KEY_ID=$(echo $credential | jq -r .Credentials.AccessKeyId)
  export AWS_SECRET_ACCESS_KEY=$(echo $credential | jq -r .Credentials.SecretAccessKey)
  export AWS_SESSION_TOKEN=$(echo $credential | jq -r .Credentials.SessionToken)
fi
