name: 'Deploy Snap'

on:
    push:
        branches:
            - setup-deployment

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install dependencies
              run: yarn install
            - name: Build
              run: yarn run build
              working-directory: packages/example

        # upload:
        #   runs-on: ubuntu-latest
        #   steps:
        #     - uses: actions/checkout@master
        #     - uses: shallwefootball/s3-upload-action@master
        #       with:
        #         aws_key_id: ${{ secrets.AWS_KEY_ID }}
        #         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        #         aws_bucket: ${{ secrets.AWS_BUCKET }}
        #         source_dir: "dirname"
