---
name: "Deploy BTC Snap to Staging"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Run Test
        run: yarn test
      - name: Build
        run: yarn run build
        working-directory: packages/example
        env:
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
          BACKEND_API_AUTH: ${{ secrets.BACKEND_API_AUTH_STAGING }}
          BACKEND_API_DOMAIN: ${{ secrets.BACKEND_API_DOMAIN_STAGING }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME_STAGING }}
      - name: publish to s3
        working-directory: packages/example
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -qq awscliv2.zip
          sudo ./aws/install --update 
          aws configure set aws_access_key_id ${{ secrets.AWS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION_STAGING }}
          aws s3 sync build/ s3://${{ secrets.BUCKET_NAME_STAGING }}/ --delete
